
export const LOAD_DESTINATIONS_SUCCESS = "LOAD_DESTINATIONS_SUCCESS";
export const LOAD_TRANSFERTYPES_SUCCESS = "LOAD_TRANSFERTYPES_SUCCESS";
export const UPDATE_DESTINATION_SUCCESS = "UPDATE_DESTINATION_SUCCESS";

export const LOAD_TAXIS_SUCCESS = "LOAD_TAXIS_SUCCESS";
export const ADD_TAXI_SUCCESS = "ADD_TAXI_SUCCESS";
export const LOAD_TAXIPOPUP_SUCCESS = "LOAD_TAXIPOPUP_SUCCESS";
export const DELETE_TAXI_SUCCESS = "DELETE_TAXI_SUCCESS";

export const SEARCH = "SEARCH";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const LOAD_KPI_SUCCESS = "LOAD_KPI_SUCCESS";

export const ALLOCATED_TO_UNALLOCATED_SUCCESS = "ALLOCATED_TO_UNALLOCATED_SUCCESS";
export const UNALLOCATED_TO_ALLOCATED_SUCCESS = "UNALLOCATED_TO_ALLOCATED_SUCCESS";
export const LOAD_ALLOCATEDPOPUP_SUCCESS = "LOAD_ALLOCATEDPOPUP_SUCCESS";
export const SAVE_ALLOCATEDPOPUP_SUCCESS = "SAVE_ALLOCATEDPOPUP_SUCCESS";
export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
export const AJAX_CALL_ERROR = "AJAX_CALL_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const ROUTE = "ROUTE";

export const REMOVE_NOTIFICATION_SUCCESS = "REMOVE_NOTIFICATION_SUCCESS";
export const CAX_MODIFIED_PUSH_NOTIFICATIONS = "CAX_MODIFIED_PUSH_NOTIFICATIONS";

export const LOAD_PRODUCT_SUCCESS = "LOAD_PRODUCT_SUCCESS";
export const LOAD_PROGRAM_SUCCESS = "LOAD_PROGRAM_SUCCESS";
export const LOAD_FLIGHTDIRECTION_SUCCESS = "LOAD_FLIGHTDIRECTION_SUCCESS";
export const LOAD_TRANSFERARTICLE_SUCCESS = "LOAD_TRANSFERARTICLE_SUCCESS";
export const LOAD_TRAINGATEWAY_SUCCESS = "LOAD_TRAINGATEWAY_SUCCESS";
export const LOAD_ACCOMMODATIONTYPE_SUCCESS = "LOAD_ACCOMMODATIONTYPE_SUCCESS";
export const FLIGHT_SEARCH = "FLIGHT_SEARCH";
export const FLIGHT_SEARCH_SUCCESS = "FLIGHT_SEARCH_SUCCESS";
export const FLIGHT_TERMINALUPDATE_SUCCESS = "FLIGHT_TERMINALUPDATE_SUCCESS";

export const AB_LOAD_STUDENTINFO_SUCCESS = "AB_LOAD_STUDENTINFO_SUCCESS";
export const AB_LOAD_WEEKTO_SUCCESS = "AB_LOAD_WEEKTO_SUCCESS";
export const AB_LOAD_WEEKFROM_SUCCESS = "AB_LOAD_WEEKFROM_SUCCESS";
export const AB_LOAD_STUDENTFILTER_SUCCESS = "AB_LOAD_STUDENTFILTER_SUCCESS";
export const AB_STUDENT_SEARCH = "AB_STUDENT_SEARCH";
export const AB_STUDENT_SEARCH_SUCCESS = "AB_STUDENT_SEARCH_SUCCESS";
export const AB_STUDENT_GENERAL_SEARCH = "AB_STUDENT_GENERAL_SEARCH";
export const AB_STUDENT_GENERAL_SEARCH_SUCCESS = "AB_STUDENT_GENERAL_SEARCH_SUCCESS";
export const AB_LOAD_STUDENTDETAILEDINFO_SUCCESS = "AB_LOAD_STUDENTDETAILEDINFO_SUCCESS";
export const AB_LOAD_ADDLOG_DROPDOWNS_SUCCESS = "AB_LOAD_ADDLOG_DROPDOWNS_SUCCESS";
export const AB_ADDLOG_SUCCESS ="AB_ADDLOG_SUCCESS";
export const AB_CONFIRMBOOKINGS_SUCCESS="AB_CONFIRMBOOKINGS_SUCCESS";
export const AB_LOAD_STUDENTJIRAINFO_SUCCESS="AB_LOAD_STUDENTJIRAINFO_SUCCESS";
export const AB_ACKNOWLEDGEBOOKINGS_SUCCESS="AB_ACKNOWLEDGEBOOKINGS_SUCCESS";
export const AB_VALIDJIRACREDENTIALS_SUCCESS="AB_VALIDJIRACREDENTIALS_SUCCESS";
export const AB_LOAD_JIRA_SUCCESS="AB_LOAD_JIRA_SUCCESS";
export const AB_LOAD_STUDENTJIRA_SUCCESS="AB_LOAD_STUDENTJIRA_SUCCESS";

export const JIRALOG = "https://jiralogs.ef.com/";

// export const API="http://localhost/LSTransportationAppAPI/";
 export const ABAPI = "http://localhost/AdminBoardAPI/";
// export const SIGNALR="http://localhost/LSTransportation.SignalR/signalr";
// export const LOGINAPI="http://localhost/LoginAPI/";

 export const API = "http://54.254.235.64/LSTransportationAppAPI/";
 //export const ABAPI = "http://54.254.235.64/AdminBoardAPI/";
 export const SIGNALR = "http://54.254.235.64/LSTransportation.SignalR/signalr";
 export const LOGINAPI = "http://54.254.235.64/LoginAPI/";

// export const API = "https://emergency.ef.com/lstransportationappapi/";
// export const ABAPI = "https://elektrasvc.ef.com/adminboardapi/";
// export const SIGNALR = "https://emergency.ef.com/lstransportation.signalr/signalr";
// export const LOGINAPI = "https://elektrasvc.ef.com/loginapi/";