export default {
    taxis: [],
    unallocatedStudents: [],
    gateways: [],
    destinations: [],
    transferTypes: [],
    ajaxCallsInProgress: 0,
    search: {},
    vehicles: [],
    user: {},
    allocatedStudent: {},
    modifiedStudents: [],
    kpi: {},
    searchLoading: false,
    programs: [],
    products: [],
    accommodationTypes: [],
    flightDirections: [],
    transferArticles: [],
    flightSearch: {},
    flightSearchResults: [],
    flightSearchLoading: false,
    path:"AirportTransfer",
    trainGateways:[],
    studentSearchResults: [],
    studentSearchLoading: false,
    studentGeneralSearchLoading: false,
    studentDetailedInfoResult:{},
    addLogDropDowns:[],
    addLogStatus: "",
    studentJiraDetailsResult:{},
    validJiraCredentials:false,
    studentLogDetailsLoading:false
};